from group6_rwa2.tasks.submit_kitting_shipment import SubmitKittingShipmentTask
from group6_rwa2.tasks.submit_assembly_shipment import SubmitAssemblyShipmentTask
from group6_rwa2.tasks.wait import WaitTask