# kitting_arm
  # - linear_arm_actuator_joint
  # - shoulder_pan_joint
  # - shoulder_lift_joint
  # - elbow_joint
  # - wrist_1_joint
  # - wrist_2_joint
  # - wrist_3_joint
  # For the gantry_torso group, the joints are:
  #   - small_long_joint
  #   - torso_rail_joint
  #   - torso_base_main_joint
  # For the gantry_arm group, the joints are:
  # - gantry_arm_shoulder_pan_joint
  # - gantry_arm_shoulder_lift_joint
  # - gantry_arm_elbow_joint
  # - gantry_arm_wrist_1_joint
  # - gantry_arm_wrist_2_joint
  # - gantry_arm_wrist_3_joint
preset_locations:
  # Home locations
  home:
    kitting_arm:  [0, 0, -1.25, 1.74, -2.04, -1.57, 0]
    gantry_full:  [-2.45, 0.0, 0.0, 0, -1.13, 1.88, -0.72, 1.55, 0.83]
    gantry_torso: [-2.45, 0.0, 0.0]
    gantry_arm:   [0, -1.13, 1.88, -0.72, 1.55, 0.83]
  home1:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-2, 0.00, 0.00, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-2, 0.00, 0.00]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  home2:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-7, 0.00, 0.00, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-7, 0.00, 0.00]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]  
  # NEAR BINS
  bin1:
    kitting_arm:  [3.52, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-0.09, -2.45, 0.0, 0, -1.13, 1.88, -0.72, 1.55, 0.83]
    gantry_torso: [-0.09, -2.45, 0.0]
    gantry_arm:   [0, -1.13, 1.88, -0.72, 1.55, 0.83]
  bin2:
    kitting_arm:  [2.70, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-0.09, -2.45, 0.0, 0, -1.13, 1.88, -0.72, 1.55, 0.83]
    gantry_torso: [-0.09, -2.45, 0.0]
    gantry_arm:   [0, -1.13, 1.88, -0.72, 1.55, 0.83]
  bin5:
    kitting_arm:  [-3.22, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-0.09, -2.45, 0.0, 0, -1.13, 1.88, -0.72, 1.55, 0.83]
    gantry_torso: [-0.09, -2.45, 0.0]
    gantry_arm:   [0, -1.13, 1.88, -0.72, 1.55, 0.83]
  bin6:
    kitting_arm:  [-2.40, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-0.09, -2.45, 0.0, 0, -1.13, 1.88, -0.72, 1.55, 0.83]
    gantry_torso: [-0.09, -2.45, 0.0]
    gantry_arm:   [0, -1.13, 1.88, -0.72, 1.55, 0.83]
  # FAR BINS
  bin3:
    kitting_arm:  [2.70, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-1.30, -2.50, -1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-1.30, -2.50, -1.57]
    gantry_arm:   [ 0, -2.01, 2.63, -0.6, 1.57, 0.83]
  bin4:
    kitting_arm:  [3.52, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-1.30, -3.4, -1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-1.30, -3.4, -1.57]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  bin7:
    kitting_arm:  [-2.40, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-1.30, 2.5, -1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-1.30, 2.5, -1.57]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  bin8:
    kitting_arm:  [-3.22, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-1.30, 3.4, -1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-1.30, 3.4, -1.57]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  # AGVs
  pre_gk_agv1:
    kitting_arm:  [4.80, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-2, -3.95, -1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-2, -3.95, -1.57]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  agv1:
    kitting_arm:  [4.80, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-0.3, -3.95, 0, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-0.3, -3.95, 0]
    # gantry_full:  [-1.60, -4.23, -1.48, 0, -2.39, 2.01, 0.38, 1.57, 0]
    # gantry_torso: [-1.60, -4.23, -1.48]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  pre_gk_agv2:
    kitting_arm:  [1.5, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-2, -0.49, -1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-2, -0.49, -1.57]
    # gantry_full:  [-1.00, -1.54, -1.48, 0, -2.39, 2.01, 0.38, 1.57, 0]
    # gantry_torso: [-1.00, -1.54, -1.48]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  agv2:
    kitting_arm:  [1.5, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-0.41, -0.49, 0, 0, -2.39, 2.01, 0.38, 1.57, 0]
    gantry_torso: [-0.41, -0.49, 0]
    # gantry_full:  [-1.00, -1.54, -1.48, 0, -2.39, 2.01, 0.38, 1.57, 0]
    # gantry_torso: [-1.00, -1.54, -1.48]
    gantry_arm:   [0, -2.39, 2.01, 0.38, 1.57, 0]
  pre_gk_agv3:
    kitting_arm:  [-1.20, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-2, 0.49, -1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-2, 0.49, -1.57]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  agv3:
    kitting_arm:  [-1.20, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-0.41, 0.49, -3.14, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-0.41, 0.49, -3.14]
    # gantry_full:  [-1.60, 1.35, -1.48, 0, -2.39, 2.01, 0.38, 1.57, 0]
    # gantry_torso: [-1.60, 1.35, -1.48]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  pre_gk_agv4:
    kitting_arm:  [-4.55, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-2, 3.82, -1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-2, 3.82, -1.57]
    # gantry_full:  [-1.00, 4.32,-1.75, 0, -2.39, 2.01, 0.38, 1.57, 0]
    # gantry_torso: [-1.00, 4.32,-1.75]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  agv4:
    kitting_arm:  [-4.55, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-0.3, 3.95, -3.14, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-0.3, 3.95, -3.14]
    # gantry_full:  [-1.00, 4.32,-1.75, 0, -2.39, 2.01, 0.38, 1.57, 0]
    # gantry_torso: [-1.00, 4.32,-1.75]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  # ==================================================================  
  # RIGHT
  agv1_as1:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-3.37, -3.8, 0, 0, -0.81, 1.55, -0.76, 1.54, 0.83]
    gantry_torso: [-3.37, -3.8, 0]
    gantry_arm:   [0, -0.81, 1.55, -0.76, 1.54, 0.83]
  agv2_as1:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-3.37, -2.2, -3.14, 0, -0.81, 1.55, -0.76, 1.54, 0.83]
    gantry_torso: [-3.37, -2.2, -3.14]
    gantry_arm:   [0, -0.81, 1.55, -0.76, 1.54, 0.83]
  agv1_as2:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-8.29, -3.8, 0, 0, -0.81, 1.55, -0.76, 1.54, 0.83]
    gantry_torso: [-8.29, -3.8, 0]
    gantry_arm:   [0, -0.81, 1.55, -0.76, 1.54, 0.83]
  agv2_as2:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-8.29, -2.1, -3.14, 0, -0.81, 1.55, -0.76, 1.54, 0.83]
    gantry_torso: [-8.29, -2.1, -3.14]
    gantry_arm:   [0, -0.81, 1.55, -0.76, 1.54, 0.83]
  # LEFT  
  agv3_as3:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-3.37, 2.2, 0, 0, -0.81, 1.55, -0.76, 1.54, 0.83]
    gantry_torso: [-3.37, 2.2, 0]
    gantry_arm:   [0, -0.81, 1.55, -0.76, 1.54, 0.83]
  agv4_as3:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-3.37, 3.8, -3.14, 0, -0.81, 1.55, -0.76, 1.54, 0.83]
    gantry_torso: [-3.37, 3.8, -3.14]
    gantry_arm:   [0, -0.81, 1.55, -0.76, 1.54, 0.83]
  agv3_as4:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-8.29, 2.2, 0, 0, -0.81, 1.55, -0.76, 1.54, 0.83]
    gantry_torso: [-8.29, 2.2, 0]
    gantry_arm:   [0, -0.81, 1.55, -0.76, 1.54, 0.83]
  agv4_as4:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-8.29, 3.9, -3.14, 0, -0.81, 1.55, -0.76, 1.54, 0.83]
    gantry_torso: [-8.29, 3.9, -3.14]
    gantry_arm:   [0, -0.81, 1.55, -0.76, 1.54, 0.83]
  # ==================================================================  
  before_as1:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-3.22, -3, 0, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-3.22, -3, 0]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  as1:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-3.82, -3, 1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-3.82, -3, 1.57]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  before_as2:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-7, -3, 0, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-7, -3, 0]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  as2:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-8.78, -3, 1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-8.78, -3, 1.57]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  before_as3:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-3.22, 3, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-3.22, 3, 0]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  as3:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-3.82, 3, 1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-3.82, 3, 1.57]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  before_as4:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-7, 3, 0, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-7, 3, 0]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]
  as4:
    kitting_arm:  [4.22, 2.14, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [-8.68, 3, 1.57, 0, -2.01, 2.63, -0.6, 1.57, 0.83]
    gantry_torso: [-8.68, 3, 1.57]
    gantry_arm:   [0, -2.01, 2.63, -0.6, 1.57, 0.83]

  # MISC
  trash_bin:
    kitting_arm:  [0.15, 3.15, -1.00, 1.87, 0.67, 1.57, 0]
    gantry_full:  [-1.00, 0.01,-1.68, 0, -1.00, 1.20, 0.38, 1.57, 0]
    gantry_torso: [-1.00, 0.01,-1.68]
    gantry_arm:   [0, -1.00, 1.20, 0.38, 1.57, 0]
  belt_cam:
    kitting_arm:  [2, 0, -1.25, 1.74, -2.09, -1.57, 0]
    gantry_full:  [0.18, -3.92, 0, -0.01, -1.10, 1.84, -0.71, 1.54, 0.83]
    gantry_torso: [0.18, -3.92, 0]
    gantry_arm:   [-0.01, -1.10, 1.84, -0.71, 1.54, 0.83]


# DIMENSIONS
bins:
  height: 0.75
agvs:
  height: 0.77
parts:
  assembly_battery_red:
    height: 0.81
  assembly_battery_green:
    height: 0.81
  assembly_battery_blue:
    height: 0.81
  assembly_sensor_red:
    height: 0.83
  assembly_sensor_green:
    height: 0.83
  assembly_sensor_blue:
    height: 0.83
  assembly_regulator_red:
    height: 0.81
  assembly_regulator_green:
    height: 0.81
  assembly_regulator_blue:
    height: 0.81
  assembly_pump_red:
    height: 0.85
  assembly_pump_green:
    height: 0.85
  assembly_pump_blue:
    height: 0.85
gripper_changing_station:
  min_x: -4.25
  max_x: -3.60
  min_y: 5.50
  max_y: 6.90
