# Multiple Kitting orders with faulty parts of multiple types with sensor black out

options:
  insert_models_over_bins: true
  belt_population_cycles: 15
  insert_models_over_stations: true
  gazebo_state_logging: true
time_limit: 500

agv_infos:
  agv1:
    location: ks1
    # products:
    #   part_0:
    #     type: assembly_battery_green
    #     pose:
    #       xyz: [0.1, 0.1, 0]
    #       rpy: [0, 0, 0]
    #   part_1:
    #     type: assembly_pump_blue
    #     pose:
    #       xyz: [-0.1, -0.1, 0]
    #       rpy: [0, 0, pi/2]
  agv2:
    location: as2
    products:
      part_0:
        type: assembly_battery_green
        pose:
          xyz: [0.1, 0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: assembly_pump_blue
        pose:
          xyz: [-0.1, -0.1, 0]
          rpy: [0, 0, pi/2]
  agv3:
    location: ks3
  agv4:
    location: ks4    
    
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 2
      agvs: [agv1, agv4]
      destinations: [as1, as4]
      products:
        part_0:
          type: assembly_sensor_green
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, pi/4]
        part_1:
          type: assembly_pump_blue
          pose:
            xyz: [-0.1, -0.15, 0]
            rpy: [pi, 0, pi/3]

  order_1:
    priority: 3 
    kitting_robot_health: 1 
    assembly_robot_health: 1
    announcement_condition: time
    announcement_condition_value: 20
    assembly:
      shipment_count: 1
      stations: [as2]
      products:
        part_0:
          type: assembly_battery_green
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_pump_blue
          pose:
            xyz: [0.032085, -0.152835, 0.25]
            rpy: [0, 0, 0]

models_over_bins:
  bin1:
    models:
      assembly_sensor_red:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2

  bin2:
    models:
      assembly_pump_red:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2
  bin3:
     models:
       assembly_pump_blue:
         xyz_start: [0.1, 0.1, 0.0]
         xyz_end: [0.5, 0.5, 0.0]
         rpy: [0, 0, pi/4]
         num_models_x: 1
         num_models_y: 1
  bin5:
    models:
      assembly_pump_blue:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2

belt_models:
  assembly_sensor_green:
    10.0:
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 'pi/2']

faulty_products:
  - assembly_pump_blue_1
  - assembly_pump_blue_4
  
# sensor_blackout:
#   product_count: 3 #sensor blackout triggered after third product is placed
#   duration: 30

